/* tslint:disable */
/* eslint-disable */
/**
 * Rivet Game API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineObject1
 */
export interface InlineObject1 {
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject1
     */
    gameModes: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject1
     */
    regions?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject1
     */
    preventAutoCreateLobby?: boolean;
}

export function InlineObject1FromJSON(json: any): InlineObject1 {
    return InlineObject1FromJSONTyped(json, false);
}

export function InlineObject1FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gameModes': json['game_modes'],
        'regions': !exists(json, 'regions') ? undefined : json['regions'],
        'preventAutoCreateLobby': !exists(json, 'prevent_auto_create_lobby') ? undefined : json['prevent_auto_create_lobby'],
    };
}

export function InlineObject1ToJSON(value?: InlineObject1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'game_modes': value.gameModes,
        'regions': value.regions,
        'prevent_auto_create_lobby': value.preventAutoCreateLobby,
    };
}


