/* tslint:disable */
/* eslint-disable */
/**
 * Rivet Game API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2001Regions
 */
export interface InlineResponse2001Regions {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Regions
     */
    regionId: string;
}

export function InlineResponse2001RegionsFromJSON(json: any): InlineResponse2001Regions {
    return InlineResponse2001RegionsFromJSONTyped(json, false);
}

export function InlineResponse2001RegionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2001Regions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'regionId': json['region_id'],
    };
}

export function InlineResponse2001RegionsToJSON(value?: InlineResponse2001Regions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'region_id': value.regionId,
    };
}


