/* tslint:disable */
/* eslint-disable */
/**
 * Rivet Game API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MatchmakerLobbyPlayer,
    MatchmakerLobbyPlayerFromJSON,
    MatchmakerLobbyPlayerFromJSONTyped,
    MatchmakerLobbyPlayerToJSON,
    MatchmakerLobbyPort,
    MatchmakerLobbyPortFromJSON,
    MatchmakerLobbyPortFromJSONTyped,
    MatchmakerLobbyPortToJSON,
    MatchmakerLobbyRegion,
    MatchmakerLobbyRegionFromJSON,
    MatchmakerLobbyRegionFromJSONTyped,
    MatchmakerLobbyRegionToJSON,
} from './';

/**
 * 
 * @export
 * @interface MatchmakerLobby
 */
export interface MatchmakerLobby {
    /**
     * 
     * @type {string}
     * @memberof MatchmakerLobby
     */
    lobbyId: string;
    /**
     * 
     * @type {MatchmakerLobbyRegion}
     * @memberof MatchmakerLobby
     */
    region: MatchmakerLobbyRegion;
    /**
     * 
     * @type {Array<MatchmakerLobbyPort>}
     * @memberof MatchmakerLobby
     */
    ports: Array<MatchmakerLobbyPort>;
    /**
     * 
     * @type {MatchmakerLobbyPlayer}
     * @memberof MatchmakerLobby
     */
    player: MatchmakerLobbyPlayer;
}

export function MatchmakerLobbyFromJSON(json: any): MatchmakerLobby {
    return MatchmakerLobbyFromJSONTyped(json, false);
}

export function MatchmakerLobbyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchmakerLobby {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lobbyId': json['lobby_id'],
        'region': MatchmakerLobbyRegionFromJSON(json['region']),
        'ports': ((json['ports'] as Array<any>).map(MatchmakerLobbyPortFromJSON)),
        'player': MatchmakerLobbyPlayerFromJSON(json['player']),
    };
}

export function MatchmakerLobbyToJSON(value?: MatchmakerLobby | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lobby_id': value.lobbyId,
        'region': MatchmakerLobbyRegionToJSON(value.region),
        'ports': ((value.ports as Array<any>).map(MatchmakerLobbyPortToJSON)),
        'player': MatchmakerLobbyPlayerToJSON(value.player),
    };
}


