/* tslint:disable */
/* eslint-disable */
/**
 * Rivet Game API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatchmakerLobbyPort
 */
export interface MatchmakerLobbyPort {
    /**
     * 
     * @type {number}
     * @memberof MatchmakerLobbyPort
     */
    source: number;
    /**
     * 
     * @type {number}
     * @memberof MatchmakerLobbyPort
     */
    target: number;
    /**
     * 
     * @type {boolean}
     * @memberof MatchmakerLobbyPort
     */
    isTls: boolean;
    /**
     * 
     * @type {string}
     * @memberof MatchmakerLobbyPort
     */
    hostname: string;
}

export function MatchmakerLobbyPortFromJSON(json: any): MatchmakerLobbyPort {
    return MatchmakerLobbyPortFromJSONTyped(json, false);
}

export function MatchmakerLobbyPortFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchmakerLobbyPort {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'source': json['source'],
        'target': json['target'],
        'isTls': json['is_tls'],
        'hostname': json['hostname'],
    };
}

export function MatchmakerLobbyPortToJSON(value?: MatchmakerLobbyPort | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'source': value.source,
        'target': value.target,
        'is_tls': value.isTls,
        'hostname': value.hostname,
    };
}


