/* tslint:disable */
/* eslint-disable */
/**
 * Rivet Game API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatchmakerLobbyRegion
 */
export interface MatchmakerLobbyRegion {
    /**
     * 
     * @type {string}
     * @memberof MatchmakerLobbyRegion
     */
    regionId: string;
    /**
     * 
     * @type {string}
     * @memberof MatchmakerLobbyRegion
     */
    displayName: string;
}

export function MatchmakerLobbyRegionFromJSON(json: any): MatchmakerLobbyRegion {
    return MatchmakerLobbyRegionFromJSONTyped(json, false);
}

export function MatchmakerLobbyRegionFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchmakerLobbyRegion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'regionId': json['region_id'],
        'displayName': json['display_name'],
    };
}

export function MatchmakerLobbyRegionToJSON(value?: MatchmakerLobbyRegion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'region_id': value.regionId,
        'display_name': value.displayName,
    };
}


